#!//bin/bash
export EPICS_CA_MAX_ARRAY_BYTES=30000000
export EPICS_DISPLAY_PATH=/local/DPbin/epics/epics_2013-04-23/synApps_5_6/support/areaDetector-1-9-1/ADApp/op/adl/:/local/DPbin/epics/epics_2013-04-23/synApps_5_6/support/all_adl

medm -x -macro "P=dp_mar165_a:, R=cam1:" marCCD.adl &
../../bin/linux-x86/marCCDApp st.cmd

