#!/bin/bash

export EPICS_CA_MAX_ARRAY_BYTES=30000000
source /local/DPbin/Scripts/Paths.bash
export EPICS_DISPLAY_PATH=$EPICS_SUPPORT/adls/

echo $EPICS_DISPLAY_PATH
medm -x -macro "P="$1":, R=cam1: " mythen.adl &
